/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MyCircle */

#ifndef _Included_MyCircle
#define _Included_MyCircle
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
